const knowledgeData = [
  {
    id: 1,
    name: "Confluence",
    url: "https://confluence.company.com",
    type: "Documentation",
    owner: "Engineering",
  },
  {
    id: 2,
    name: "Jira",
    url: "https://id.atlassian.com/login",
    type: "Issue Tracking",
    owner: "Engineering",
  },
  {
    id: 3,
    name: "ServiceNow",
    url: "https://www.servicenow.com/login",
    type: "ITSM",
    owner: "Operations",
  },
  {
    id: 4,
    name: "Splunk",
    url: "https://login.splunk.com",
    type: "Monitoring",
    owner: "SRE Team",
  },
  {
    id: 5,
    name: "Grafana",
    url: "https://grafana.com/login",
    type: "Dashboard",
    owner: "Monitoring",
  },
  {
    id: 6,
    name: "Prometheus",
    url: "https://prometheus.io",
    type: "Metrics",
    owner: "Monitoring",
  },
  {
    id: 7,
    name: "Red Hat Portal",
    url: "https://access.redhat.com",
    type: "Vendor Support",
    owner: "Platform Team",
  },
  {
    id: 8,
    name: "DB Assist Portal",
    url: "https://dbassist.com",
    type: "Internal Portal",
    owner: "Database Team",
  },
  {
    id: 9,
    name: "CyberArk",
    url: "https://cyberark.company.com",
    type: "PAM",
    owner: "Security Team",
  },
  {
    id: 10,
    name: "LDAP Portal",
    url: "https://ldap.company.com",
    type: "Authentication",
    owner: "IAM Team",
  },
  {
    id: 11,
    name: "GitHub Enterprise",
    url: "https://github.com/login",
    type: "Source Code",
    owner: "Development",
  },
  {
    id: 12,
    name: "OpenSearch",
    url: "https://opensearch.company.com",
    type: "Log Analytics",
    owner: "SRE Team",
  },
  {
    id: 13,
    name: "Kubernetes Dashboard",
    url: "https://k8s.company.com",
    type: "Container Platform",
    owner: "DevOps",
  },
  {
    id: 14,
    name: "ArgoCD",
    url: "https://argocd.company.com",
    type: "CI/CD",
    owner: "DevOps",
  },
  {
    id: 15,
    name: "API Gateway",
    url: "https://gateway.company.com",
    type: "API Management",
    owner: "Integration Team",
  },
    {
    id: 16,
    name: "Payment Hub",
    url: "https://gateway.company.com",
    type: "Payment Management",
    owner: "Integration Team",
  },
];

export default knowledgeData;