const connectorData = [
  {
    id: 1,
    name: "CyberArk",
    type: "IAM",
    status: "Connected",
    lastSync: "2 min ago",
    response: "120 ms",
    version: "v14",
    action: "View",
  },
  {
    id: 2,
    name: "Splunk",
    type: "Monitoring",
    status: "Connected",
    lastSync: "1 min ago",
    response: "90 ms",
    version: "v9",
    action: "Test",
  },
  {
    id: 3,
    name: "LDAP",
    type: "Directory",
    status: "Connected",
    lastSync: "10 min ago",
    response: "100 ms",
    version: "v3",
    action: "Sync",
  },
  {
    id: 4,
    name: "Jira",
    type: "Ticketing",
    status: "Failed",
    lastSync: "2 hrs ago",
    response: "Timeout",
    version: "Cloud",
    action: "Retry",
  },
  {
    id: 5,
    name: "Slack",
    type: "Notification",
    status: "Connected",
    lastSync: "5 min ago",
    response: "80 ms",
    version: "v2",
    action: "Test",
  },
  {
    id: 6,
    name: "AI Engine",
    type: "AI",
    status: "Connected",
    lastSync: "20 sec ago",
    response: "40 ms",
    version: "1.2",
    action: "View",
  },
];

export default connectorData;