const auditData = [
  {
    id: "AUD-1001",
    user: "Kapil Gandhi",
    role: "Admin",
    action: "Login",
    module: "Authentication",
    status: "Success",
    ip: "10.15.20.45",
    device: "Windows 11",
    browser: "Chrome",
    severity: "Low",
    description: "Administrator logged into the application successfully.",
    time: "10:15 AM",
    date: "24 Jul 2026"
  },
  {
    id: "AUD-1002",
    user: "Kapil Gandhi",
    role: "Admin",
    action: "Password Reset",
    module: "Settings",
    status: "Success",
    ip: "10.15.20.45",
    device: "Windows 11",
    browser: "Chrome",
    severity: "Medium",
    description: "Password reset completed.",
    time: "10:20 AM",
    date: "24 Jul 2026"
  },
  {
    id: "AUD-1003",
    user: "Rahul Singh",
    role: "L2",
    action: "Updated Incident",
    module: "Incident Manager",
    status: "Success",
    ip: "10.10.15.7",
    device: "Dell Laptop",
    browser: "Edge",
    severity: "Medium",
    description: "Updated incident severity and owner.",
    time: "10:35 AM",
    date: "24 Jul 2026"
  },
  {
    id: "AUD-1004",
    user: "AI System",
    role: "Service",
    action: "Generated Resolution",
    module: "AI Engine",
    status: "Success",
    ip: "Internal",
    device: "Service",
    browser: "-",
    severity: "Low",
    description: "AI generated incident resolution.",
    time: "10:40 AM",
    date: "24 Jul 2026"
  },
  {
    id: "AUD-1005",
    user: "John",
    role: "Viewer",
    action: "Delete User",
    module: "User Management",
    status: "Failed",
    ip: "192.168.1.12",
    device: "MacBook",
    browser: "Safari",
    severity: "Critical",
    description: "User attempted to delete another user without permission.",
    time: "10:45 AM",
    date: "24 Jul 2026"
  },
  {
    id: "AUD-1006",
    user: "CyberArk Sync",
    role: "System",
    action: "Role Synchronization",
    module: "CyberArk",
    status: "Success",
    ip: "Internal",
    device: "Service",
    browser: "-",
    severity: "Low",
    description: "CyberArk roles synchronized successfully.",
    time: "09:50 AM",
    date: "24 Jul 2026"
  },
  {
    id: "AUD-1007",
    user: "Scheduler Service",
    role: "System",
    action: "Daily Health Check",
    module: "Scheduler",
    status: "Success",
    ip: "Internal",
    device: "Service",
    browser: "-",
    severity: "Low",
    description: "Scheduler health check completed successfully.",
    time: "09:55 AM",
    date: "24 Jul 2026"
  },
  {
    id: "AUD-1008",
    user: "Splunk",
    role: "Monitoring",
    action: "Email Trigger",
    module: "Alert Engine",
    status: "Success",
    ip: "Internal",
    device: "Server",
    browser: "-",
    severity: "Medium",
    description: "Failure notification email sent.",
    time: "09:58 AM",
    date: "24 Jul 2026"
  },
  {
    id: "AUD-1009",
    user: "Database Admin",
    role: "DBA",
    action: "Backup Started",
    module: "Database",
    status: "Success",
    ip: "10.10.1.15",
    device: "Linux Server",
    browser: "-",
    severity: "Low",
    description: "Nightly PostgreSQL backup started.",
    time: "08:30 AM",
    date: "24 Jul 2026"
  },
  {
    id: "AUD-1010",
    user: "Scheduler Service",
    role: "System",
    action: "Job Failed",
    module: "Scheduler",
    status: "Failed",
    ip: "Internal",
    device: "Service",
    browser: "-",
    severity: "High",
    description: "Scheduler failed due to database timeout.",
    time: "08:45 AM",
    date: "24 Jul 2026"
  }
];

export default auditData;